### ISSUE TITLE
Issues with the config.yaml.sample file

### ISSUE THREAD

**Issue by Mariangela** [wso2/puppet-common#1]
The following issues were identified with the [config.yaml.sample](https://github.com/wso2/puppet-common/blob/master/vagrant/config.yaml.sample) file.
1. hostname: wso2esb.4.9.0.dev.wso2.org should change to  hostname: esb.dev.wso2.org 
2. pattern: pattern_01 should change to pattern: pattern-1
3. Point 1&2 needs to be done in the commented out sample as well.

Please note that the latter points were tested and verified with API Manager 2.0.0 default profile before being reported.

**Comment by imesh** [comment]
Thanks for reporting this Mari! All of the above points are now fixed with commit 69be4ea5b623873b10b3c862809c72537ca38e26.
