### ISSUE TITLE
Some product profiles are not defined in site.pp

### ISSUE THREAD

**Issue by Mariangela** [wso2/puppet-common#3]
The following product profiles are not defined in [site.pp](https://github.com/wso2/puppet-common/blob/master/manifests/site.pp)
- [tm.dev.wso2.org](https://github.com/wso2/puppet-apim/blob/master/hieradata/dev/wso2/wso2am/pattern-2/traffic-manager.yaml)
- [mgt.esb.dev.wso2.org](https://github.com/wso2/puppet-esb/blob/master/hieradata/dev/wso2/wso2esb/pattern-2/manager.yaml)
- [ESB Worker](https://github.com/wso2/puppet-esb/blob/master/hieradata/dev/wso2/wso2esb/pattern-2/worker.yaml) - Hostname not defined for profile as well.
- [is.dev.wso2.org](https://github.com/wso2/puppet-is/blob/master/hieradata/dev/wso2/wso2is/pattern-1/default.yaml)
- [is.dev.wso2.org](https://github.com/wso2/puppet-is/blob/master/hieradata/dev/wso2/wso2is/pattern-1/key-manager.yaml) - The WSO2 IS default and key manager profiles have the same hostname, unlike in API Manager where every profile has different hostnames. Is this correct?
- [is.dev.wso2.org](https://github.com/wso2/puppet-is/blob/master/hieradata/dev/wso2/wso2is/pattern-2/default.yaml)
- [is.dev.wso2.org](https://github.com/wso2/puppet-is/blob/master/hieradata/dev/wso2/wso2is/pattern-2/key-manager.yaml) - The WSO2 IS default and key manager profiles have the same hostname, unlike in API Manager where every profile has different hostnames. Is this correct?

**Comment by imesh** [comment]
Hostname-based initialization was removed in site.pp by adding a [default](https://github.com/wso2/puppet-common/blob/master/manifests/site.pp#L19) section. This approach would work for any hostname when Hieradata is used. If Hieradata is not used required hostnames need to be added according to the puppet modules used.
